"""Initial Migration

Revision ID: 746a4f80890c
Revises: f18b4af4b780
Create Date: 2022-02-13 16:48:57.502990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746a4f80890c'
down_revision = 'f18b4af4b780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
